### ISSUE TITLE
can't get data from API in Java. Please help.

### ISSUE THREAD

**Issue by Sammers21** [stevschmid/track-o-bot#175]
i would get string from
 "https://trackobot.com/profile/history.json?username=cool-ancient-tree-1337&token=fhyf238cv2eh879" 
for example.

source code:
`public class Main {
public static void main(String[] args) throws Exception {
	// write your code here
        String content = getText("https://trackobot.com/profile/history.json?username=cool-ancient-tree-1337&token=fhyf238cv2eh879");
        System.out.println(content);
    }

 public static String getText(String url) throws Exception {
        URL website = new URL(url);
        HttpsURLConnection connection = (HttpsURLConnection)website.openConnection();
        connection.connect();
        BufferedReader in = new BufferedReader(
                new InputStreamReader(
                        connection.getInputStream()));

        StringBuilder response = new StringBuilder();
        String inputLine;

        while ((inputLine = in.readLine()) != null)
            response.append(inputLine);

        in.close();

        return response.toString();
    }
}`
an error occurs in the line
' connection.connect();' 
the error text : 
"Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.company.Main.getText(Main.java:19)
	at com.company.Main.main(Main.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
"
write please what am I doing wrong. thanks for the reply

**Comment by stevschmid** [comment]
Google: http://stackoverflow.com/questions/30758303/problems-connecting-via-https-ssl-through-own-java-client
